# Generated by Django 5.2.6 on 2025-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='id источника')),
                ('source_name', models.CharField(max_length=70, verbose_name='название источника')),
                ('author', models.CharField(blank=True, max_length=70, null=True, verbose_name='автор')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('url', models.URLField(unique=True, verbose_name='ссылка')),
                ('url_to_image', models.URLField(blank=True, null=True, verbose_name='ссылка на картинку')),
                ('published_at', models.DateTimeField(verbose_name='дата публикации')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
